### ISSUE TITLE
Main subs only

### ISSUE THREAD

**Issue by darkhelmet2016** [seiya-dev/crunchyroll-downloader-nx#1]
** Main info: **

Script version: 
4.3.0
Show ID: 
Episode ID: 

** Additional Info: **
Will it be possible to add a switch to download one sub instead of all of them like if you want like just English or Spanish since a lot of shows have both Español and Español (España)? Almost forgot that 
Português is the same and has (Brasil) and (Portugal) when you may want one or the other and not both. Or if you are in the UK since it might not pull or download the enUK subs since it has a different hard sub tag from the enUS sub if you are trying to get the GB site links instead.

**Comment by seiya-git** [comment]
in future release will be added

**Comment by seiya-git** [comment]
added in latest release
