### ISSUE TITLE
Exception when starting to download

### ISSUE THREAD

**Issue by Kitt3120** [seiya-dev/crunchyroll-downloader-nx#10]
**Error**:
(node:5675) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at fnOutputGen (/home/myuser/Tools/crunchyroll-downloader-nx/crunchy.js:1004:10)
    at getMedia (/home/myuser/Tools/crunchyroll-downloader-nx/crunchy.js:584:16)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async getShowById (/home/myuser/Tools/crunchyroll-downloader-nx/crunchy.js:529:13)
(node:5675) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5675) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate 

**Description**:
Wanted to download a full Anime, seems like the script can't load something correctly and the exception is also not handled correctly.

**System**:
Script version: 4.9.0
Show ID: 22193
Episode ID: 1-24
Node.js Version: 12.6.0
Linux: Manjaro 4.19.59-1
Country: Germany

**Comment by seiya-git** [comment]
can you show what u put in cli and your main config yaml?

**Comment by Kitt3120** [comment]
Little note: This completely worked on my Debian machine, but not on arch somehow. I made sure that everything is set up correctly tho.

**config.main.yml**:
bin:
  ffmpeg: /usr/bin/ffmpeg
  mkvmerge: /usr/bin/mkvmerge
dir:
  content: /mnt/Media/CrunchyRoll/
  trash: /mnt/Media/CrunchyRoll/_trash/
cli:
  releaseGroup: CR
  fileSuffix: SIZEp
  videoQuality: max
  dubLanguage: jpn
  mp4mux: false
  noCleanUp: false
  nServer: 1
  oldSubs: false
#eof

I used the
-s 22193
-e 1-24
flags

**Comment by seiya-git** [comment]
filenameTemplate is missing from config file
https://github.com/seiya-dev/crunchyroll-downloader-nx/blob/master/modules/config.main.yml

**Comment by Kitt3120** [comment]
Oh, okay.. lol. I did a fresh github clone tho ¯\_(ツ)_/¯

It works now! Thank you :)

**Comment by seiya-git** [comment]
https://github.com/seiya-dev/crunchyroll-downloader-nx/releases/latest
fixed in latest release
