### ISSUE TITLE
Unable to pull subs

### ISSUE THREAD

**Issue by darkhelmet2016** [seiya-dev/crunchyroll-downloader-nx#4]
** Main info: **

Script version: 
4.3.1
Show ID: 
Episode ID: 

** Additional Info: **
Requesting: [783344] YU-NO: A Girl Who Chants Love at the Bound of This World (D
ub) - E01 - You Know?
[ERROR] No available full streams!
[INFO] Downloading subtitles...
[WARN] Can't find urls for subtitles! If you downloading sub version, try use ol
dsubs cli option

Trying the old subs switch gives a 404.
[ERROR] No available full streams!
[INFO] Downloading subtitles...
[INFO] Trying get subtitles in old format...
[ERROR] HTTPError 404: Not Found
[ERR] Can't get video id for subtitles list!

Seems it needs the cookie data or it can not find the values for subs or streams. Had to log back in  but then it muxed in the audio as being Japanese for the Dub. Audio: AAC 44100Hz stereo [A: Japanese [jpn] (aac lc, 44100 Hz, stereo) [default]]

**Comment by seiya-git** [comment]
That's strange. All works fine for me. Do you have premium account?
Dub not always correctly detected, you need use dub option `--dub eng`

**Comment by darkhelmet2016** [comment]
It seems to have an issue if the show is not present on vrv at the time or if it can not pull the url from vrv and it will return a 404 even when trying the fallback servers.

**Comment by seiya-git** [comment]
try new version, but before it, please relogin
