### ISSUE TITLE
Show search detection

### ISSUE THREAD

**Issue by darkhelmet2016** [seiya-dev/crunchyroll-downloader-nx#5]
** Main info: **
Script version: 
4.3.1
Show ID: 
Episode ID: 

** Additional Info: **
Movies like https://www.crunchyroll.com/a-wind-named-amnesia use the same series id for both sub and dub so they are not picked up separately during a search.

[INFO] Search Results:
[SERIES] #273483 A Wind Named Amnesia
  [S:23529] A Wind Named Amnesia

In addition searching with too many results causers  session and cookie data to be overwritten.
[INFO] Cookies were updated! (session_id)
Would a pause function fix this or locking the cookie data during a search?

**Comment by seiya-git** [comment]
1) session_id stores for 1 hour
![image](https://user-images.githubusercontent.com/7394323/57968119-101a4a80-796f-11e9-807a-a7488133ba02.png)
2) use `-s 23529 -e s1` for dub
use `-s 23529 -e s2` for sub

**Comment by darkhelmet2016** [comment]
C:\Users\Owner\crunchyroll>node crunchy --search "A Wind Named Amnesia"

=== Crunchyroll Downloader NX 4.3.1 ===

[INFO] Search Results:
[SERIES] #273483 A Wind Named Amnesia
  [S:23529] A Wind Named Amnesia

[INFO] Total results: 1


C:\Users\Owner\Desktop\crunchyroll>

Like said when doing a search for a title. As in using the search parameters.

**Comment by seiya-git** [comment]
cookie updating is fixed with new version
