### ISSUE TITLE
MP4 with sub muxing issue

### ISSUE THREAD

**Issue by darkhelmet2016** [seiya-dev/crunchyroll-downloader-nx#6]
** Main info: **

Script version: 
4.3.1
Show ID: 
Episode ID: 

** Additional Info: **
Using the outputs --mp4 and -mks does not convert the subs to srt and mux them in to the mp4 container.
[mpegts @ 049c4ac0] start time for stream 2 is not set in estimate_timings_from_
pts

**Comment by seiya-git** [comment]
it's not possible convert ass subs to srt, because ass have typesettings

**Comment by darkhelmet2016** [comment]
it is possible, have done it with another program that will do it for crunchy subs. youtube-dl does it "https://github.com/ytdl-org/youtube-dl --convert-subs FORMAT  Convert the subtitles to other format  (currently supported: srt|ass|vtt|lrc)

**Comment by seiya-git** [comment]
i look into it later

**Comment by seiya-git** [comment]
added in latest release
