### ISSUE TITLE
Download Whole Series Instead of Seasons

### ISSUE THREAD

**Issue by KannaDev** [seiya-dev/crunchyroll-downloader-nx#7]
** Main info: **

Script version: 4.3.1 stable
Show ID: 
Episode ID: 

** Additional Info: ** The way the script currently works is it requires a `-s` (series id) and a `-e` (range of episodes to download) params. It gets really hard to download shows with so many seasons like One Piece.

Can there be an update that basically takes in a show id, rather than a series id and default `-e` to total number of episodes in the whole "Show" not "Season".

**Comment by seiya-git** [comment]
you can create batch file using ranges of all episodes `-s XXXX -e 1-1000`
non existence episodes in range will be skipped
