### ISSUE TITLE
[ERROR] No available full streams / Session expired!

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [seiya-dev/crunchyroll-downloader-nx#8]
** Main info: **

Script version: 4.3.2
Show ID: 24660
Episode ID: 778851

first time trying to use this & i keep getting this error:

i use the following arguments: -q 1080p -s 24660 -e 1-12

Requesting: [778851] Hand Shakers (English Dub) - E01 - Conductor to Contact
[ERROR] No available full streams / Session expired!
[INFO] Downloading subtitles...
[INFO] Downloaded: [CR] Hand Shakers (English Dub) - 01 [1080p].200619 eng English (US).ass

i'm not sure why its throwing the Session expired! error even though i can watch videos from crunchyroll just fine..

**Comment by XxUnkn0wnxX** [comment]
@seiya-git 
not a OS issue. i get same error in windows, & ANY VPN's i try i ever tried several earlier versions of script & i getting same error. including different with different account & i have tried other show ids

**Comment by XxUnkn0wnxX** [comment]
also downloading via
`youtube-dl` --cookies cookies.txt https://www.crunchyroll.com/hand-shakers/episode-4-live-lab-778856 --sub-format ass --sub-lang enUS --audio-format aac`

has no issues either. seems only with ur script seems to be failing to login/keep session alive.

**Comment by seiya-git** [comment]
because of session_id, it's not updated if you change your ip. try use `--nosess` option

**Comment by seiya-git** [comment]
https://github.com/seiya-dev/crunchyroll-downloader-nx/releases/tag/4.3.3
not session cookie problem, seems they added new type of streams
