### ISSUE TITLE
Features Request

### ISSUE THREAD

**Issue by Fray117** [seiya-dev/crunchyroll-downloader-nx#9]
Hi, wonder it would be great if several features like:

1. Auto Action Take (i think this would be great since people may downloading many episodes, so when they want to leave the task wil be cleared automatically)
2. Preset Configuration like Proxy or Something (more again for batch download user, they more likely download lot, so how about make they just set config and download with their preset)
3. better ffmpeg interface (i like the stuff with mp4 muxing, however it sucks when i meet too much verbose that should be just 1 line like wget do, but it seems come from ffmpeg it self, i don't tried mkvmerge at this moment)

**Main info:**

Script version:  4.7.0

**Comment by seiya-git** [comment]
1. What you mean auto action?
2. Just edit `config.main.yml`
3. If you need mkv better use mkvmerge, for mp4 only ffmpeg
